CREATE DATABASE Livraria;
USE Livraria;

CREATE TABLE Cliente (
idCliente INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
tipo VARCHAR(20) NOT NULL,
cpf VARCHAR(14),
cnpj VARCHAR(18),
cep VARCHAR(9) NOT NULL
);

CREATE TABLE Autor (
idAutor INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nome VARCHAR(150) NOT NULL,
nacionalidade VARCHAR(40) NOT NULL,
biografia VARCHAR(500)
);


CREATE TABLE Editor(
idEditor INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
cnpj VARCHAR(18) NOT NULL,
cidade VARCHAR(45) NOT NULL,
pais VARCHAR(45) NOT NULL
);

CREATE TABLE Categoria(
idCategoria INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
descricao VARCHAR(50) NOT NULL,
titulo VARCHAR(100) UNIQUE NOT NULL
);


CREATE TABLE Livro(
idLivro INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
titulo VARCHAR(150) UNIQUE,
descritivo VARCHAR(100),
ano DATE,
preco DECIMAL
);

CREATE TABLE Livro_has_Categoria(
idLivro INT PRIMARY KEY,
idCategoria INT PRIMARY KEY,
PRIMARY KEY (idLivro, idCategoria),
FOREIGN KEY (idLivro) REFERENCES Livro(id),
FOREIGN KEY (idCategoria) REFERENCES Categoria(id)
);
CREATE TABLE Transportadora (
idTransportadora INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nome VARCHAR(45) NOT NULL,
cnpj VARCHAR(18) NOT NULL,
cep VARCHAR(8) NOT NULL
);

CREATE TABLE Venda(
numeroNotaFiscal VARCHAR(400) AUTO_INCREMENT NOT NULL PRIMARY KEY,
data DATETIME NOT NULL,
valorTotal FLoat NOT NULL
);

CREATE TABLE Entrega(
numeroNotaFiscal VARCHAR(400) AUTO_INCREMENT NOT NULL PRIMARY KEY,
idTransportadora INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
numeroProtocolo INT NOT NULL PRIMARY KEY,
FOREIGN KEY (numeroNotaFiscal) REFERENCES 


